# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da0381a35090e153f051aa6c19cee5c6f265d3fbcf941aa043d2db80093829426ee3e59f8b37cae414866880cb4911814de731f3750775ec598342b0e58e6d34

test:
  secret_key_base: 9e22bfdce6f78dd6a6cf51df64bd17431a7146531e6e993da91c5c83598bb927af5b34a67b2b0536a2f938956f3254d10f59530f1abd135c7bef0c53eeff6098

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
